FROM python:3.10

WORKDIR /app

RUN git clone https://github.com/dpsec26/conduit-backend.git .

#COPY ./backend/settings.py /app/conduit/settings.py

COPY ./backend/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE ${BACKEND_PORT}
ENTRYPOINT [ "/app/entrypoint.sh" ]