FROM python:3.10-slim

WORKDIR /app

COPY ./backend/ /app/

COPY ./entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080
ENTRYPOINT [ "/app/entrypoint.sh" ]