name: Conduit Container Deployment

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      # login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      # build and push backend
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.backend
          tags:  ghcr.io/${{ github.repository_owner }}/conduit-backend:${{ github.sha }}
          push: true
      # build and push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          tags:  ghcr.io/${{ github.repository_owner }}/conduit-frontend:${{ github.sha }}
          push: true
      # create env file
      - name: Create env file
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
          echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> .env
          echo "DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}" >> .env
          echo "DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}" >> .env
          echo "DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DB_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
      # copy setup files to vm
      - name: Copy setup files to remote host
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "docker-compose-deployment.yaml,.env"
          target: "/tmp"
      # ssh into vm
      - name: Pull and start containers on remote host
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            set -e
            TARGET_DIR="conduit"
            mkdir -p $TARGET_DIR
            cd $TARGET_DIR
            mv /tmp/docker-compose-deployment.yaml docker-compose.yaml
            mv /tmp/.env .
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
            export REPOSITORY_OWNER=${{ github.repository_owner }}
            export FRONTEND_IMAGE_TAG=${{ github.sha }}
            export FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
            export BACKEND_IMAGE_TAG=${{ github.sha }}
            export BACKEND_PORT=${{ secrets.BACKEND_PORT }}
            docker compose pull
            docker compose down
            docker compose up -d
            docker logout ghcr.io